[build]
  functions = "functions"  # Make sure Netlify runs your Flask backend
  command = "pip install --quiet -r requirements.txt"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
