[build]
  # The directory containing the functions (Flask app in this case)
  functions = "netlify/functions"
  
  # The base directory where your project files are (use an empty string for root directory)
  base = ""
  
  # Command to install dependencies
  command = "pip install -r requirements.txt"
  
  # Publish directory for your app (Lambda functions in the "functions" directory)
  publish = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
