[build]
  base = ""
  publish = "/"
  functions = "functions"
  command = "pip install -r requirements.txt && python functions/app.py"

[context.production.environment]
  SESSION_SECRET = "secure-512"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true
