[build]
  functions = "functions"  # Remove "rdcic/functions", just use "functions"
  command = "pip install --quiet -r requirements.txt"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
