[build]
  functions = "functions"  # Do not include "rdcic/functions"
  command = "pip install --quiet -r requirements.txt"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
